### ISSUE TITLE
Copy doesn't copy weapon

### ISSUE THREAD

**Issue by victorb** [Guad/MissionCreator#1]
Hello there! Awesome mod, love it so far!

However, seems like the copy function doesn't copy everything. Tried copying an actor with a weapon and it doesn't keep the weapon. The rest seems to be fine.

**Comment by Guad** [comment]
It does copy the weapon, just the ped doest wield it at that session. Try saving &  loading the map, they'll have it out.

**Comment by victorb** [comment]
Ooh, I see. My mistake. Thanks for the ultrafast reply :+1:
